FROM ubuntu:18.04

RUN apt-get update

# Install fbexport
RUN apt-get install -y g++ make libfbclient2

COPY . /build/fbexport
WORKDIR /build/fbexport
RUN make LIBEFBCLIENT=libfbclient.so.3.0.2
RUN cp exe/fbexport /usr/local/bin
RUN cp exe/fbcopy /usr/local/bin

# Install firebird 3.0
RUN apt-get install -y firebird3.0-server firebird3.0-utils

# Load data to init empty db with meta
RUN mkdir -p /etc/firebird/3.0/init
ADD db_create.sql /etc/firebird/3.0/init
ADD db_meta.sql /etc/firebird/3.0/init
ADD db_auth.sql /etc/firebird/3.0/init

# ARGS
ARG FIREBIRD_DATABASE="28dc98d6-4df0-5e57-bf3b-ea36413990b3"
ENV FIREBIRD_DATABASE=$FIREBIRD_DATABASE

VOLUME ["/firebird"]

# Create database
COPY create-empty-db.sh /usr/local/bin/create-empty-db.sh
RUN chmod +x /usr/local/bin/create-empty-db.sh

ENTRYPOINT ["/usr/local/bin/create-empty-db.sh"]