FROM ubuntu:18.04 as builder

RUN apt-get update

# Build fbexport
RUN apt-get install -y g++ make libfbclient2

COPY . /build/fbexport
WORKDIR /build/fbexport
RUN make LIBEFBCLIENT=libfbclient.so.3.0.2
RUN cp exe/fbexport /usr/local/bin
RUN cp exe/fbcopy /usr/local/bin

FROM ubuntu:18.04
COPY --from=builder /usr/local/bin/fbexport /usr/local/bin
COPY --from=builder /usr/local/bin/fbcopy /usr/local/bin

RUN apt-get update
# Install firebird 3.0
RUN apt-get install -y firebird3.0-server firebird3.0-utils
# envsubst
RUN apt-get install -y gettext

# Load data to init empty db with meta
RUN mkdir -p /etc/firebird/3.0/init
ADD tables.conf /etc/firebird/3.0/init
ADD db_create.sql /etc/firebird/3.0/init
ADD db_meta.sql /etc/firebird/3.0/init
ADD db_auth.sql /etc/firebird/3.0/init

# Create database
COPY docker-entrypoint.sh /usr/local/bin/
COPY database-init.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]