s/CHARACTER SET \(NONE\|WIN1251\)/CHARACTER SET UTF8/gI
s/CHAR(\([0-9]\+\))\(,\|)\)/CHAR(\1) CHARACTER SET UTF8\2/gI
s/BLOB SUB_TYPE TEXT/BLOB SUB_TYPE TEXT CHARACTER SET UTF8/g
s/COLLATE PXW_CYRL/COLLATE UNICODE_CI/gI
s/COLLATE WIN1251/COLLATE UNICODE_CI/gI
s/VARCHAR(30000)/BLOB SUB_TYPE TEXT/gI
s/SEGMENT SIZE 1024//g
s/SEGMENT SIZE 128/SEGMENT SIZE 4096/g
s/SEGMENT SIZE 80/SEGMENT SIZE 4096/g
s/SEGMENT SIZE 1//g